#!/bin/bash

### COMMAND LINE OPTIONS        
while [[ $1 == -* ]]
do
    case "$1" in

      -a|--add)
              shift
              tag="$1" ; shift
              duedate="$1" ; shift 
              text="$@" ; test_date ;;

      -d|--due)
              shift 
              duedate="$@"
              recall_due ;;

      -dc)
              shift
              duedate="$@"
              recall_due_cons ;;

      -x|--del)
              del_line ;;

      -xr|--rdel)
              rdel_line ;;

      -e|--edit)
              "$taskfer_editor" "$tasklist"
              exit 0 ;;
                 
      -h|--help|-\?)
              show_help
              exit 0 ;;

      -i|--interactive)
              ask_entry ;;

      -k|--key|--keyword)
              key="$2"
              recall_keyword ;;

      -l|--list)
              show_cal
              sort -t"|" -k2 "$tasklist" | \
              awk -F"|" '{ print $1 "\t" $2 $3 }' | "$taskfer_pager"
              kill_cal
              exit 0 ;;
                
      -r|--recur|--recurrent)
              recurrent ;;

      -t|--tag)
              tag="$2"
              recall_tag ;;
               
      -tc)
              tag="$2"
              recall_tag_cons ;;
           
      -w|--week)
              if [[ "$2" ]]
              then 
                  days="$2"
              else
                  days=8 
              fi 
              recall_week ;;
                
      -wc)
              if [[ "$2" ]]
              then
                  days="$2"
              else
                  days=8
              fi
              recall_week_cons ;;
           
      --clean)
              clean_old ;;
      
      -c)
              printf "\n\t You must use the full option, \"--clean\" \n"
              printf "\t to delete all the old entries. \n\n"
                  1>&2; exit 1 ;;

       *) 
              printf "\t invalid option: $1 \n\n"
              printf "\t Try:  $0 -h for full help. \n\n"
                  1>&2; exit 1 ;;
    esac
done




### COMMAND LINE OPTIONS        
while [[ $1 == -* ]]
do
    case "$1" in
      -a|-add) shift ; tag="$1" ; shift ; duedate="$1" ; shift ; text="$@" ; test_date ;;
      -d|-due) shift ; duedate="$@" ; recall_due ;;
      -dc) shift ; duedate="$@" ; recall_due_cons ;;
      -x|-del|--del) del_line ;;
      -xr|-rdel|--rdel) rdel_line ;;
      -e|-edit) "$taskfer_editor" "$tasklist" ; exit 0 ;;
      -h|--help|-\?) show_help; exit 0;;
      -i) ask_entry ;;
      -k|-key) key="$2" ; recall_keyword ;;
      -l|-list) show_cal ; sort -t"|" -k2 "$tasklist" | awk -F"|" '{ print $1 "\t" $2 $3 }' | "$taskfer_pager" ; kill_cal ; exit 0 ;;
      -r|-recur) recurrent ;;
      -t|-tag) tag="$2" ; recall_tag ;;
      -tc) tag="$2" ; recall_tag_cons ;;
      -w|-week) if [[ "$2" ]] ; then days="$2" ; else days=8 ; fi ; recall_week ;;
      -wc) if [[ "$2" ]] ; then days="$2" ; else days=8 ; fi ; recall_week_cons ;;
      -clean) clean_old ;;
       *) printf "\t invalid option: $1 \n\n"
          printf "\t Try:  $0 -h for full help. \n\n"
                  1>&2; exit 1
                  ;;
    esac
done


       *) echo "
    invalid option: $1
    
    $0 -h for full help.
    "
                1>&2; exit 1;;
