#!/usr/bin/env bash


function show_help {
    printf "$help_text" 
    exit 0
}

help_text="\n 
  Usage: $0  <option> [arguments]\n
  valid options: 
       -a                 add/append entry to task list. Free-form dates with
                          spaces need to be quoted. 
                              todo -a <tag> <due-date> <message>
                          
       -d [due date]      recall entries by due date, quotes not needed.
                          No argument shows tasks due today.

       -x, -del           delete a line from the task list
                          
       -e                 edit the task list. 

       -h, --help, -?,    display this help and exit

       -k <key words>     recall entries by keyword or phrase

       -l                 list all entries. 

       -r <tag>           recall entries by tag
       
       "

show_help
