#!/usr/bin/env bash

testfer_dir=$HOME/.testfer



echo "
    The default location for the config file
    and working files for taskfer is in
    testdir/

    Answer yes to accept the default
    or enter a different path: 
    "
read answer
while true ; do
    case "$answer" in
        [Yy]*) break ;;
            *) sed -i~ 's/$HOME\/\.testfer/'"$answer/" test_setup
             testfer_dir="$answer" ; echo "this $testfer_dir" ;  break ;;
    esac
done

if ! [[ -d $testfer_dir ]]
    then
        mkdir $testfer_dir
fi
echo "Here it is: $testfer_dir"

function add_rc {
#rcfile="/$testfer_dir/testferrc"
default_values="
#testferrc
# Configuration file for testfer task manager
# Edit these variables as desired, or use the defaults.
testlist=${testlist:=$testfer_dir/testlist}
tmplist=${tmplist:=$testfer_dir/tmplist}
testfer_pager=${testfer_pager:=$(which less)}
testfer_editor=${testfer_editor:=$(which vim)}
"
echo "$default_values" > "$testfer_dir/testferrc"
}

add_rc
cat "$testfer_dir/testferrc"
exit 0
